services:
  # meta service will be ignored by compose
  .victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v1.42.0
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
      - -datadog.streamFields=service,hostname,ddsource
      - -journald.streamFields=_HOSTNAME,_SYSTEMD_UNIT,_PID
      - -journald.ignoreFields=MESSAGE_ID,INVOCATION_ID,USER_INVOCATION_ID
      - -journald.ignoreFields=_BOOT_ID,_MACHINE_ID,_SYSTEMD_INVOCATION_ID,_STREAM_ID,_UID
    deploy:
      replicas: 0
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

  vmauth:
    image: docker.io/victoriametrics/vmauth:v1.132.0
    restart: on-failure
    volumes:
      - ./:/etc/vmauth
    command: -auth.config=/etc/vmauth/vmauth.yml
    ports:
      - '8427:8427'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8427/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    depends_on:
      victorialogs-1:
        condition: service_healthy
      victorialogs-2:
        condition: service_healthy

  victorialogs-1:
    extends: .victorialogs
    volumes:
      - victorialogs-1:/vlogs
    deploy:
      replicas: 1

  victorialogs-2:
    extends: .victorialogs
    volumes:
      - victorialogs-2:/vlogs
    deploy:
      replicas: 1

  vlagent:
    image: victoriametrics/vlagent:v1.41.0
    volumes:
      - vlagent:/vlagent
    command:
      - '--remoteWrite.tmpDataPath=/vlagent'
      - '--remoteWrite.url=http://victorialogs-1:9428/insert/native'
      - '--remoteWrite.url=http://victorialogs-2:9428/insert/native'
      - '--syslog.listenAddr.tcp=0.0.0.0:8094'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9429/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    depends_on:
      victorialogs-1:
        condition: service_healthy
      victorialogs-2:
        condition: service_healthy

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.132.0
    command:
      - -storageDataPath=/vmsingle
      - -loggerFormat=json
    volumes:
      - victoriametrics:/vmsingle
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  victorialogs-1:
  victorialogs-2:
  victoriametrics:
  vlagent:
